# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Untitled.ui'
#
# Created: Sat Apr 12 00:35:22 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(669, 678)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtCore.Qt.PointingHandCursor)
        MainWindow.setMouseTracking(True)
        MainWindow.setWhatsThis("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtGui.QGraphicsView(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(30, 10, 161, 171))
        self.photo.setObjectName("photo")
        self.Name = QtGui.QLineEdit(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(220, 10, 221, 21))
        self.Name.setText("")
        self.Name.setObjectName("Name")
        self.commens = QtGui.QPlainTextEdit(self.centralwidget)
        self.commens.setGeometry(QtCore.QRect(30, 270, 441, 151))
        font = QtGui.QFont()
        self.commens.setFont(font)
        self.commens.setObjectName("commens")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 240, 151, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Surname = QtGui.QLineEdit(self.centralwidget)
        self.Surname.setGeometry(QtCore.QRect(220, 40, 221, 21))
        self.Surname.setObjectName("Surname")
        self.Phone = QtGui.QLineEdit(self.centralwidget)
        self.Phone.setGeometry(QtCore.QRect(220, 70, 221, 21))
        self.Phone.setObjectName("Phone")
        self.City = QtGui.QLineEdit(self.centralwidget)
        self.City.setGeometry(QtCore.QRect(220, 100, 221, 21))
        self.City.setObjectName("City")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 10, 81, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 40, 81, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 70, 111, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 100, 61, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 190, 61, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.main_tech = QtGui.QLineEdit(self.centralwidget)
        self.main_tech.setGeometry(QtCore.QRect(220, 130, 221, 21))
        self.main_tech.setObjectName("main_tech")
        self.minor_tech = QtGui.QLineEdit(self.centralwidget)
        self.minor_tech.setGeometry(QtCore.QRect(220, 160, 221, 21))
        self.minor_tech.setObjectName("minor_tech")
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 160, 81, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(460, 130, 81, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Level = QtGui.QComboBox(self.centralwidget)
        self.Level.setGeometry(QtCore.QRect(220, 190, 221, 26))
        self.Level.setObjectName("Level")
        self.save = QtGui.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(493, 590, 131, 32))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.save.setFont(font)
        self.save.setObjectName("save")
        self.save.clicked.connect(self.printout)
        self.upload = QtGui.QPushButton(self.centralwidget)
        self.upload.setGeometry(QtCore.QRect(493, 560, 131, 32))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.upload.setFont(font)
        self.upload.setObjectName("upload")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 220, 591, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(600, 10, 16, 211))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 10, 20, 211))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(30, 190, 91, 23))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.CV = QtGui.QPlainTextEdit(self.centralwidget)
        self.CV.setGeometry(QtCore.QRect(30, 440, 441, 181))
        self.CV.setObjectName("CV")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 420, 151, 20))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.upload_CV = QtGui.QToolButton(self.centralwidget)
        self.upload_CV.setGeometry(QtCore.QRect(500, 530, 121, 23))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.upload_CV.setFont(font)
        self.upload_CV.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.upload_CV.setWhatsThis("")
        self.upload_CV.setObjectName("upload_CV")
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(487, 510, 131, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 669, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Name, self.Surname)
        MainWindow.setTabOrder(self.Surname, self.Phone)
        MainWindow.setTabOrder(self.Phone, self.City)
        MainWindow.setTabOrder(self.City, self.main_tech)
        MainWindow.setTabOrder(self.main_tech, self.minor_tech)
        MainWindow.setTabOrder(self.minor_tech, self.Level)
        MainWindow.setTabOrder(self.Level, self.commens)
        MainWindow.setTabOrder(self.commens, self.CV)
        MainWindow.setTabOrder(self.CV, self.upload_CV)
        MainWindow.setTabOrder(self.upload_CV, self.upload)
        MainWindow.setTabOrder(self.upload, self.save)


    def printout(self):
        self.text = self.Name.text()
        print self.text

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Rucruter 1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Surname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Phone number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "City", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Minor tech.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Main tech.", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Save changes, locally</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.upload.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Sinc. with Google Drive</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.upload.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Path to profile photo</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "Upload Photo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "CV", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_CV.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Path to CV file</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_CV.setText(QtGui.QApplication.translate("MainWindow", "Upload CV", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))




class ControlMainWindow(QtGui.QMainWindow):
  def __init__(self, parent=None):
    super(ControlMainWindow, self).__init__(parent)
    self.ui =  Ui_MainWindow()
    self.ui.setupUi(self)
   
if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    mySW = ControlMainWindow()
    mySW.show()
    sys.exit(app.exec_())



